plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'me.modmuss50.mod-publish-plugin' version "${modmuss50_mod_publish_version}"
    id 'com.diffplug.spotless'
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${neo_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
            gameDirectory = this.mkdir(this.file('runs/client'))
        }
        server {
            server()
            gameDirectory = this.mkdir(this.file('runs/server'))
        }
        configureEach {
            ideName = "Forge ${it.name.capitalize()} (${project.path})"
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1")) {
        version {
            strictly '[0.1, 1.0)'
            prefer '0.4.1'
        }
    }
    modImplementation "mod.azure.azurelib:azurelib-neo-${minecraft_version}:${azurelib_version}"
    modImplementation "curse.maven:spark-361579:4738952"
}

jar {
    finalizedBy('reobfJar')
    manifest.attributes([
        "MixinConfigs": "${mod_id}.forge.mixins.json"
    ])
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")
if (keyPropsFile.exists()) {
    publishMods {
        def releaseProp = new Properties()
        releaseProp.load(new FileInputStream(keyPropsFile))
        def jarFile = file("build/libs/ovomorphosis-forge-${minecraft_version}-${project.version}.jar")
        file = jarFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("forge")

        curseforge {
            projectId = project.curseforgeID
            projectSlug = project.projectSlug
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "azurelib"
            }
            javaVersions.add(JavaVersion.VERSION_17)
            client = true
            server = true
        }
        modrinth {
            projectId = project.modrinthID
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add("${minecraft_version}")
            requires {
                slug = "azurelib"
            }
            environment = CLIENT_AND_SERVER
        }
    }
}
