plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'com.diffplug.spotless'
}

neoForge {
    neoFormVersion = "${neoform_version}"

    accessTransformers = ["../common/src/main/resources/META-INF/accesstransformer.cfg"]
}

dependencies {
    compileOnly('net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7')
    compileOnly(annotationProcessor('io.github.llamalad7:mixinextras-common:0.5.3'))
    compileOnly "mod.azure.azurelib:azurelib-common-${minecraft_version}:${azurelib_version}"
    compileOnly "com.azure.azurecortex:azurecortex-common-${minecraft_version}:${azurecortex_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava(sourceSets.main.java.srcDirs.find { it.exists() })
    commonResources(sourceSets.main.resources.srcDirs.find { it.exists() })
}